import time


# This function simulates sending text to Huawei ModelArts
def generate_summary_from_modelarts(text_content):
    """
    Input: Text from the student's note.
    Output: A summary generated by MindSpore.
    """
    # TODO: Replace this with actual 'requests.post()' to your ModelArts Endpoint

    # SIMULATION FOR DEMO:
    time.sleep(1)  # Fake processing time
    return f"This is a MindSpore-generated summary of the text: {text_content[:50]}..."


def generate_quiz_from_modelarts(text_content):
    # SIMULATION
    return [
        {"question": "What is the main topic?", "options": ["A", "B", "C"], "answer": "A"},
        {"question": "Who is the author?", "options": ["X", "Y", "Z"], "answer": "X"}
    ]